# Your project's server will run on localhost:xxxx at this port
PORT: 8000

# Autoprefixer will make sure your CSS works with these browsers
COMPATIBILITY:
  - "last 2 versions"
  - "ie >= 9"
  - "ios >= 7"

# UnCSS will use these settings
UNCSS_OPTIONS:
  html:
    - "app/**/*.html"
  ignore:
    - !!js/regexp .foundation-mq
    - !!js/regexp ^\.is-.*

# Gulp will reference these paths when it copies files
PATHS:
  # Path to dist folder
  dist: "dist"
  dist_1:
    - "dist/assets/**/*"
    - "!dist/assets/{imgs,js,css,}{,/**/*}"
  # Paths to static assets that aren't images, CSS, or JavaScript
  assets:
    - "app/assets/**/*"
    - "!app/assets/{imgs,js,scss,combineJs}{,/**/*}"
  # Paths to Sass libraries, which can then be loaded with @import
  sass:
    - "node_modules/foundation-sites/scss"
    - "node_modules/motion-ui/src"
  # Paths to JavaScript entry points for webpack to bundle modules
  entries:
    - "app/assets/js/app.js"


# Gulp will reference these info when sftp
DEPLOY:
  host: ""
  user: ""
  password: ""
  # Static remote patch
  remote: "public_html"